// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slices

type _Float32 struct{}

func (_ _Float32) Range(start, end int) []float32 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]float32, l)
	for i := 0; i < l; i += 1 {
		res[i] = float32(start + i)
	}
	return res
}

var Float32T _Float32

type _Float64 struct{}

func (_ _Float64) Range(start, end int) []float64 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]float64, l)
	for i := 0; i < l; i += 1 {
		res[i] = float64(start + i)
	}
	return res
}

var Float64T _Float64

type _Int struct{}

func (_ _Int) Range(start, end int) []int {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]int, l)
	for i := 0; i < l; i += 1 {
		res[i] = int(start + i)
	}
	return res
}

var IntT _Int

type _Int16 struct{}

func (_ _Int16) Range(start, end int) []int16 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]int16, l)
	for i := 0; i < l; i += 1 {
		res[i] = int16(start + i)
	}
	return res
}

var Int16T _Int16

type _Int32 struct{}

func (_ _Int32) Range(start, end int) []int32 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]int32, l)
	for i := 0; i < l; i += 1 {
		res[i] = int32(start + i)
	}
	return res
}

var Int32T _Int32

type _Int64 struct{}

func (_ _Int64) Range(start, end int) []int64 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]int64, l)
	for i := 0; i < l; i += 1 {
		res[i] = int64(start + i)
	}
	return res
}

var Int64T _Int64

type _Int8 struct{}

func (_ _Int8) Range(start, end int) []int8 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]int8, l)
	for i := 0; i < l; i += 1 {
		res[i] = int8(start + i)
	}
	return res
}

var Int8T _Int8

type _Uint struct{}

func (_ _Uint) Range(start, end int) []uint {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]uint, l)
	for i := 0; i < l; i += 1 {
		res[i] = uint(start + i)
	}
	return res
}

var UintT _Uint

type _Uint16 struct{}

func (_ _Uint16) Range(start, end int) []uint16 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]uint16, l)
	for i := 0; i < l; i += 1 {
		res[i] = uint16(start + i)
	}
	return res
}

var Uint16T _Uint16

type _Uint32 struct{}

func (_ _Uint32) Range(start, end int) []uint32 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]uint32, l)
	for i := 0; i < l; i += 1 {
		res[i] = uint32(start + i)
	}
	return res
}

var Uint32T _Uint32

type _Uint64 struct{}

func (_ _Uint64) Range(start, end int) []uint64 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]uint64, l)
	for i := 0; i < l; i += 1 {
		res[i] = uint64(start + i)
	}
	return res
}

var Uint64T _Uint64

type _Uint8 struct{}

func (_ _Uint8) Range(start, end int) []uint8 {
	l := end - start
	if l < 0 {
		l = 0
	}
	res := make([]uint8, l)
	for i := 0; i < l; i += 1 {
		res[i] = uint8(start + i)
	}
	return res
}

var Uint8T _Uint8
